(docs) Update brew install instructions
homebrew released version 2.7.0 on December 21st

announcement blog: https://brew.sh/2020/12/21/homebrew-2.7.0/

In the change notes under the item "Additional API deprecations,
disables and removals." this PR is linked:

https://github.com/Homebrew/brew/pull/10056

In this PR, `brew cask` was moved from deprecated to disabled. If users
try to install software this way, they get a message like this now:

```
$ brew cask install puppetlabs/puppet/pdk
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 7 formulae.
==> Updated Casks
Updated 2 casks.

Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```